COIN_IDS = {
    'btc': 'bitcoin', 'eth': 'ethereum', 'xrp': 'ripple', 'bch': 'bitcoin-cash', 'ltc': 'litecoin', 
    'eos': 'eos', 'bnb': 'binancecoin', 'xtz': 'tezos', 'xmr': 'monero', 'ada': 'cardano', 
    'dash': 'dash', 'xlm': 'stellar', 'leo': 'unus-sed-leo', 'trx': 'tron', 'ht': 'huobi-token', 
    'neo': 'neo', 'etc': 'ethereum-classic', 'link': 'chainlink', 'usdc': 'usd-coin', 'cro': 'crypto-com-coin', 
    'atom': 'cosmos', 'miota': 'iota', 'xem': 'nem', 'vet': 'vechain', 'zec': 'zcash', 
    'bat': 'basic-attention-token', 'qtum': 'qtum', 'tusd': 'trueusd', 'pax': 'paxos-standard-token', 'doge': 'dogecoin', 
    'dcr': 'decred', 'rvn': 'ravencoin', 'waves': 'waves', 'algo': 'algorand', 'dai': 'dai', 
    'omg': 'omg-network', 'mkr': 'maker', 'rep': 'augur', 'kcs': 'kucoin-shares', 'lsk': 'lisk', 
    'btg': 'bitcoin-gold', 'dgb': 'digibyte', 'snt': 'status', 'zrx': '0x', 'ont': 'ontology', 
    'nano': 'nano', 'bts': 'bitshares', 'icx': 'icon', 'hot': 'holo', 'enj': 'enjin-coin', 
    'comp': 'compound', 'snx': 'synthetix-network-token', 'zil': 'zilliqa', 'yfi': 'yearn-finance', 'uma': 'uma', 
    'busd': 'binance-usd', 'aave': 'aave', 'band': 'band-protocol', 'ren': 'ren', 'lrc': 'loopring', 
    'knc': 'kyber-network', 'bal': 'balancer', 'srn': 'sirin-labs-token', 'ant': 'aragon', 'stx': 'blockstack', 
    'btcv': 'bitcoin-vault', 'gnt': 'golem', 'mco': 'mco', 'rdn': 'raiden-network-token', 'storj': 'storj', 
    'rlc': 'iexec-rlc', 'mana': 'decentraland', 'bnt': 'bancor', 'grt': 'the-graph', 'uni': 'uniswap', 
    'sol': 'solana', 'dot': 'polkadot', 'avax': 'avalanche', 'sushi': 'sushiswap', 'fil': 'filecoin', 
    'cel': 'celsius-network-token', 'theta': 'theta-token', 'cake': 'pancakeswap-token', 'aergo': 'aergo', 'cvc': 'civic', 
    '1inch': '1inch', 'chz': 'chiliz', 'egld': 'elrond', 'flow': 'flow', 'ftt': 'ftx-token', 
    'hbar': 'hedera-hashgraph', 'hedg': 'hedgetrade', 'hex': 'hex', 'hnt': 'helium', 'ksm': 'kusama', 
    'luna': 'terra-luna', 'near': 'near-protocol', 'nft': 'apenft', 'okb': 'okb', 'sand': 'the-sandbox', 
    'shib': 'shiba-inu', 'steth': 'steth', 'stmx': 'stormx', 'sxp': 'swipe', 'tel': 'telcoin', 
    'tfuel': 'theta-fuel', 'tomo': 'tomochain', 'trx': 'tron', 'ust': 'terrausd', 'vet': 'vechain', 
    'woo': 'wootrade-network'
}
